### ISSUE TITLE
API compatibility

### ISSUE THREAD

**Issue by tramhao** [Nirusu99/ytd-rs#1]
Hello and thanks for the great lib. I'm using it in my app and it's very convenient.

However, a recent change 0.1.6 break api compatibility of the code. I've fixed it, but I have a little suggestion, would you please change version to like 0.2 for api compatibility change? This will not affect the code I published in crates.io because I use ytd-rs=0.1 in cargo.toml . 
Thanks so much.

**Comment by narrrl** [comment]
I'm sry, that was completely dumb from me to release breaking changes as a revision. From now on I'll release revisions `0.1.x` without any breaking api changes.
